# Generated by Django 4.1.2 on 2023-02-10 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='preview_en',
            field=models.CharField(max_length=244, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='preview_ky',
            field=models.CharField(max_length=244, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='preview_ru',
            field=models.CharField(max_length=244, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ky',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='voting_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.voting'),
        ),
        migrations.AddField(
            model_name='news',
            name='voting_ky',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.voting'),
        ),
        migrations.AddField(
            model_name='news',
            name='voting_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.voting'),
        ),
    ]
