# Generated by Django 4.1.2 on 2023-02-10 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_news_content_en_news_content_ky_news_content_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='voting_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='voting_ky',
        ),
        migrations.RemoveField(
            model_name='news',
            name='voting_ru',
        ),
    ]
